CREATE DATABASE IF NOT EXISTS trek_site;
USE trek_site;
DROP TABLE IF EXISTS trek_images;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS trek_category;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS treks;
DROP TABLE IF EXISTS users;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(100) UNIQUE, email VARCHAR(150) UNIQUE, password VARCHAR(255), role ENUM('admin','user') DEFAULT 'user', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE treks (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, slug VARCHAR(255) UNIQUE NOT NULL, short_desc VARCHAR(512), long_desc TEXT, price DECIMAL(10,2) NOT NULL, location VARCHAR(150), duration VARCHAR(50), difficulty ENUM('Easy','Moderate','Hard') DEFAULT 'Moderate', start_dates TEXT, seats INT DEFAULT 0, is_featured TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE trek_images (id INT AUTO_INCREMENT PRIMARY KEY, trek_id INT NOT NULL, filename VARCHAR(255) NOT NULL, is_cover TINYINT(1) DEFAULT 0, FOREIGN KEY (trek_id) REFERENCES treks(id) ON DELETE CASCADE);
CREATE TABLE categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) UNIQUE);
CREATE TABLE trek_category (trek_id INT, category_id INT, PRIMARY KEY (trek_id,category_id), FOREIGN KEY (trek_id) REFERENCES treks(id) ON DELETE CASCADE, FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE);
CREATE TABLE bookings (id INT AUTO_INCREMENT PRIMARY KEY, trek_id INT NOT NULL, user_id INT, name VARCHAR(200), email VARCHAR(150), phone VARCHAR(50), booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, travel_date DATE, seats INT DEFAULT 1, amount_paid DECIMAL(10,2) DEFAULT 0, status ENUM('pending','confirmed','cancelled') DEFAULT 'pending', FOREIGN KEY (trek_id) REFERENCES treks(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL);
INSERT INTO users (username, email, password, role) VALUES ('admin','admin@example.com','$2y$10$wH9dMZQb4lq0JY0HsZ9kVOG5x1VJXW/rw2ZQZK6rZy1QFqQ9k9Z9W','admin');
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Harishchandragad Trek via Pachnai','harishchandragad-via-pachnai','Classic sunrise trek near Pune.','Pachnai route offering iconic Konkankada views.',1399,'Pune','1 Night 1 Day','Moderate','2025-12-05,2025-12-12,2025-12-19',40,1);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Kalsubai Sunrise Trek','kalsubai-sunrise-trek','Climb Kalsubai, Maharashtra''s highest peak.','Night trek with ladders and sunrise views.',1299,'Pune','1 Night 1 Day','Moderate','2025-11-30,2025-12-07,2025-12-21',45,1);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Rajgad Fort Trek','rajgad-fort-trek','Historic fort with caves and machis.','Explore Rajgad fort and ancient ruins.',999,'Pune','1 Day','Moderate','2025-12-01,2025-12-15,2025-12-29',50,0);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Sinhagad Fort Sunrise Trek','sinhagad-sunrise-trek','Quick sunrise trek near Pune.','Sunrise, local snacks and short climb.',499,'Pune','Half Day','Easy','2025-11-27,2025-12-03,2025-12-10',60,0);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Lohagad Fort Trek','lohagad-fort-trek','Monsoon favorite with Vinchu Kata.','Beautiful views and forts near Lonavala.',699,'Lonavala','1 Day','Easy','2025-12-08,2025-12-16,2025-12-30',50,0);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Visapur Fort Trek','visapur-fort-trek','Waterfalls and ruins near Lonavala.','Long ascent with panoramic valley views.',799,'Lonavala','1 Day','Moderate','2025-12-06,2025-12-13,2025-12-20',50,1);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Torana Fort Trek','torana-fort-trek','Challenging steep ascents.','For experienced trekkers only.',899,'Pune','1 Day','Hard','2025-12-14,2025-12-21',35,0);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Tikona Fort Trek','tikona-fort-trek','Triangular fort with Pawna Lake view.','Family-friendly trail.',699,'Lonavala','1 Day','Easy','2025-12-04,2025-12-18',50,0);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Andharban Jungle Trek','andharban-jungle-trek','Dense forest trail with waterfalls.','Scenic green trails near Tamhini.',1499,'Tamhini','1 Day','Moderate','2025-12-11,2025-12-25',40,1);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Devkund Waterfall Trek','devkund-waterfall-trek','Hidden blue lagoon waterfall.','Forest trek ending at picturesque falls.',999,'Bhira','1 Day','Easy','2025-12-05,2025-12-19',60,1);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Raireshwar Plateau Trek','raireshwar-plateau-trek','Plateau with temples and views.','Great for beginners and kids.',799,'Bhor','1 Day','Easy','2025-12-07,2025-12-14,2025-12-28',50,0);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Sandhan Valley Trek','sandhan-valley-trek','Valley of Shadows with rappelling.','Adventure plus overnight camping.',2199,'Igatpuri','2 Days','Hard','2025-12-06,2025-12-20',30,1);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Bhigwan Flamingo Watching','bhigwan-flamingo-watching','Birdwatching trip for flamingos.','Seasonal migratory bird spectacle.',1499,'Daund','1 Day','Easy','2025-12-13,2025-12-27',40,0);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Bhimashankar Jungle Trek','bhimashankar-trek','Dense forest and sacred jyotirlinga.','Wildlife and steep ascents.',1199,'Khed','1 Day','Moderate','2025-12-10,2025-12-17',45,0);
INSERT INTO treks (title,slug,short_desc,long_desc,price,location,duration,difficulty,start_dates,seats,is_featured) VALUES ('Malshej Ghat Waterfall Trek','malshej-ghat-waterfall-trek','Monsoon paradise with waterfalls.','Fog, streams and many cascades.',1099,'Malshej','1 Day','Easy','2025-12-08,2025-12-22',50,0);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (1, 'trek_1.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (2, 'trek_2.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (3, 'trek_3.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (4, 'trek_4.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (5, 'trek_5.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (6, 'trek_6.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (7, 'trek_7.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (8, 'trek_8.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (9, 'trek_9.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (10, 'trek_10.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (11, 'trek_11.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (12, 'trek_12.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (13, 'trek_13.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (14, 'trek_14.jpg', 1);
INSERT INTO trek_images (trek_id, filename, is_cover) VALUES (15, 'trek_15.jpg', 1);